apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-service
  namespace: istio-demo
spec:
  type: NodePort
  selector:
    app: nginx-frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
