apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
  namespace: istio-demo
spec:
  type: ClusterIP
  selector:
    app: node-backend
  ports:
  - port: 3030
    targetPort: 3000
    name: http
    protocol: TCP
