apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend-deploy-v2
  namespace: istio-demo
spec:
  selector:
    matchLabels:
      app: nginx-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-frontend
        version: v2
    spec:
      containers:
      - name: nginx-frontend
        image: frontend:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
